### ISSUE TITLE
Viz2 file upload does not work

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1002]
I go to the Files page in Viz 2, browse to a state log file, select State as the file type, and poke Upload. Nothing happens. I can copy files into the user space, but very few users would discover how to do that, and I think a local tool should have full access to the local filesystem.

**Comment by erikkemperman** [comment]
We noticed the same thing, but I thought it was resolved by https://github.com/powertac/powertac-server/commit/baef7006531af889874f7d1f2e229552da4d29f2 — I assume you’re on latest master, and so it’s still broken? I’ll look at it on Monday!

**Comment by erikkemperman** [comment]
hi John,

Sorry for not getting back to this earlier, have been unwell for a couple of days.

I am unable to reproduce this, if I upload a state file (precisely as you describe) it works as expected -- the file is under /files/admin/log and appears in the list in the GUI. I've tested with PowerTAC_2018_Finals_1.state, which is just under the limit of 1GB.

Can you send me a link to the file that is not working for you?

**Comment by jecollins** [comment]
In general, I think the "security" in viz2 is both broken and unnecessary. Why can I not just select a state log when I want a weather file or a seed file? Why do all the files disappear after each game. I have to log out and log back in to see the files again. It's really very annoying.

**Comment by erikkemperman** [comment]
That’s clearly not how it’s supposed to work, I will try to reproduce your issue again on Monday. Sorry that it’s annoying.

In general, the “security” is inherent to jhipster, it would (have) be(en) a ton of work to get rid of it, and basically make subsequent upgrades next to impossible because we’d have diverged even further from their trunk.

Provided of course that things work properly, it seems to me a minor inconvenience to have to spend a few seconds to log in once a session. And we actually discussed this early on, and found an upside for potential multi-user instances.

Also, could you provide me the file that’s not uploading for you properly?

**Comment by jecollins** [comment]
Here's what the file-picker dialog looks like when I try to run a second game. It's been an hour or more since I ran the last game, but I've had this problem with shorter intervals. A little googling turns up a clue about an expired token. Is there a timeout we can disable or extend to a ridiculously large value?
![error-dialog](https://user-images.githubusercontent.com/274899/52819125-295ce380-306e-11e9-8aa3-31ed6671a99b.png)

**Comment by erikkemperman** [comment]
Apparently you can set server.session.timeout (in seconds) in src/main/resources/config/application.yml — and you should probably then also make sure that server.session.cookie.max-age (also in seconds) is at least as large.

Haven’t tried this myself though, not at a computer at the moment.

**Comment by jecollins** [comment]
Thanks. When I try to edit the yaml, I get a message that server.session.timeout and server.session.cookie.* are deprecated, replaced by server.servlet.session.... I'll let you know if it does not work.

**Comment by jecollins** [comment]
[This bug report](https://github.com/jhipster/generator-jhipster/issues/7096) recommends against using sessions at all for JHipster.

**Comment by erikkemperman** [comment]
I’m pretty sure Julien means that cookie-based sessions are not currently recommended, compared to alternatives such as jwt — not that you shouldn’t have sessions period. But these alternatives, which are now their default, weren't implemented when we first started viz2. The only available choice other than cookie at the time was http basic-auth.

**Comment by jecollins** [comment]
Setting the two timeout values solves the problem
