### ISSUE TITLE
2018 csv file format breaks assumptions about game ID values

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1003]
Prior to 2018, the tournament csv file had a "gameId" column in which the value corresponded to the game number in the gameName and the name of the logfile. This is not the case for 2018, which breaks assumptions in analysis code we've written to pull down and process log files. The gameId values in the 2018 file seem to have no relationship to anything relevant.

The current csv file should be repaired, and the code that creates it should be fixed to avoid this problem in the future.

**Comment by jecollins** [comment]
It would also help tremendously if the naming of logfiles is standardized. In recent years the name  (nn is the game number) has been "finals_yyyy_mm_nn", "finals_yyyy_mm_nn-sim",  "powertac-sim-nn", and "PowerTAC_Finals_yyyy_nn". Also, the naming of the csv file has been inconsistent - for 2018 it was "finals_2018_07.games_.csv" but in 2017 it was "finals_2017_06.games.csv". These inconsistencies make it unnecessarily difficult to write analysis scripts that can be used across multiple tournaments.

Since logs are bundled with boot logs in separate subdirectories from sim logs, the name does not need to distinguish between boot and sim sessions. Unless we intend to run games that are not Power TAC games with this infrastructure, it's not clear that "PowerTAC" needs to be part of the name. It's conceivable that we would want to run multiple tournaments in a year. Therefore I recommend that the log names be "tt_yyyy_mm_nn" where tt is the tournament type -- finals, qual, trial, etc.

**Comment by govertbuijs** [comment]
I've requested the current file to be replaced (incl. name) on the site with an updated version.

The names of the tournaments have been updated to result in the following log structure.
Filename : finals_2019_07_1.tar.gz

`├── boot-log
│   ├── finals_2019_07_1.state
│   ├── finals_2019_07_1.trace
│   ├── init.state
│   └── init.trace
├── finals_2019_07_1.xml
└── log
    ├── finals_2019_07_1.state
    ├── finals_2019_07_1.trace
    ├── init.state
    └── init.trace
`

**Comment by jecollins** [comment]
Looks good. Thanks!
