### ISSUE TITLE
Server should be able to run for at least a simulated year

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1031]
It currently runs out of memory around six months

**Comment by jecollins** [comment]
Updated OrderbookRepo. WeatherReportRepo, and WeatherForecastRepo to limit the data they hold. Ran a 50-week sim with the Sample Broker without problems. That was using the web interface, which itself keeps a lot of data around to render its graphs.

**Comment by jecollins** [comment]
Ran a full 2-year sim. No errors.

**Comment by jecollins** [comment]
The fix seems to have broken replay-from-file.

**Comment by jecollins** [comment]
Problem was trying to initialize repos before the clock was set in the file-replay mode. Fixed with lazy initialization.

**Comment by Sanjay-14BIT009** [comment]
@jecollins I am trying to run a PowerTAC game for a simulated year by modifying the values of common.competition.minimumTimeslotCount and common.competition.expectedTimeslotCount. I have kept both the values as 8400 timeslots (350 days of simulation). However, the games are stopping after approximately 1400 timeslots (60 days of simulation). Please let me know if I need to configure any other parameters to make the server run for one simulation year.
