### ISSUE TITLE
Error with fresh setup of stable version #1036

### ISSUE THREAD

**Issue by Sanjay-14BIT009** [powertac/powertac-server#1042]
Please see issue #1036. I'm still facing the same problem.

I am able to run sample-broker 1.7.0 without any problem with 1.7 version of server.

But I'm getting the same error while running sample-broker 1.6.0 with Power TAC distribution 1.7.0-SNAPSHOT. Our broker is built upon sample-broker 1.6.0 , so it is also throwing the same error.

I tried local install of powertac-core as you said in one of the comments, but it didn't help.

Software Configurations:
JAVA : java version "11.0.5" 2019-10-15 LTS
Maven : Apache Maven 3.6.0

Kindly help me to resolve this issue.

**Comment by jecollins** [comment]
There appears to be an incompatible mismatch in the Apache MQ setup between the 1.6.0 and 1.7.0-SNAPSHOT versions of the server. But your broker is in source form; it works to just tell it to use the 1.7.0-SNAPSHOT version of broker-core and its dependencies. You can do that by editing sample-broker/pom.xml, changing the string 1.6.0 to 1.7.0-SNAPSHOT in two places. I have tested this with a fresh download of the sample-broker 1.6.0 source.

Please let us know if this solves your problem.

**Comment by Sanjay-14BIT009** [comment]
Thanks for quick reply.

That worked. Now I'm able to run our brokers with server 1.7 with Java11.

But I have broker binaries of other brokers (.jar files), how to make them run in this setting ?

**Comment by jecollins** [comment]
I'm working on that. Ideally it could be handled on the server, but might require editing a config file in the broker.

**Comment by Sanjay-14BIT009** [comment]
Okay. Thanks for your help.
