### ISSUE TITLE
Snapshot 1.8 not available on Sonatype

### ISSUE THREAD

**Issue by phipag** [powertac/powertac-server#1053]
Hello,
it seems that the 1.8 snapshot of the server-distribution is not yet available on Sonatype even though required in the `pom.xml` as of commit 075cd20ab46d2d276f25a9389b9af1fbcbfb5ee8.

Maven throws the following error:
`[FATAL] Non-resolvable parent POM for org.powertac:server-distribution:1.8.0-SNAPSHOT: Could not find artifact org.powertac:powertac-server:pom:1.8.0-SNAPSHOT in sonatype (https://oss.sonatype.org/content/repositories/snapshots/) and 'parent.relativePath' points at no local POM @ line 15, column 11`

**Comment by jecollins** [comment]
I apologize for not getting it deployed. I was running a few additional tests and got distracted. It's there now.
