### ISSUE TITLE
Simulation terminates after a few timeslots

### ISSUE THREAD

**Issue by stavrosgreece** [powertac/powertac-server#1107]
Hello,

In the last few days, I am trying to run simple simulations using the powerTAC server but the simulation terminates after a few timeslots.
The same problem even occurs when I am trying to create a new bootstrap file.

To replicate this problem:

1. I run the visualizer2 using any command for example "mvn -Pweb2"
2. I select the option "I want to run a bootstrap game ..."
3. I use a new name for the game and leave the rest options to default, then I start the game
4. The game starts and it gets the game status "Running"
5. After a few seconds the game "finishes", without having completed the simulation, the same happens to simple simulation games.

After that, I get a warning message (I am not sure if this is related to the problem though):
"WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/root/.m2/repository/com/thoughtworks/xstream/xstream/1.4.17/xstream-1.4.17.jar) to field java.util.Properties.defaults"

I have tried this on 3 different PCs, 2 of them running Ubuntu 20.04 and the other Windows 10 and I get the same results.

Could it be something that I do wrong or is this a server-side problem?

Thanks!

**Comment by jecollins** [comment]
The problem is that the weather server now requires an https:// URL. I will update the snapshot, test it, and let you know. This will be a problem for both the current 1.9.0-SNAPSHOT and for the 1.8.0 versions. If we need to do a new 1.8 release to fix this, I can do that if it's important.

**Comment by jecollins** [comment]
Snapshot is updated, tested, and deployed. Please let me know if you need an updated release for the 1.8 server.

**Comment by stavrosgreece** [comment]
Thanks John for the fast reply, the 1.9 version of the PowerTAC server works as intended now.

I do not think we will need the 1.8 version though.

**Comment by stavrosgreece** [comment]
Hello,

I am reopening this thread because I have the same problem when trying to run a simulation.

**Comment by jecollins** [comment]
This is happening due to [a critical security bug in log4j](https://thehackernews.com/2021/12/extremely-critical-log4j-vulnerability.html). We have a fix, should be deployed today or tomorrow.

**Comment by govertbuijs** [comment]
John is correct, as a precaution we shut down all services.
The weather server is back up.
