### ISSUE TITLE
Server not running for a full simulated year

### ISSUE THREAD

**Issue by Sanjay-14BIT009** [powertac/powertac-server#1135]
This is regarding issue #1031. I am trying to run a PowerTAC game for a simulated year by modifying the values of common.competition.minimumTimeslotCount and common.competition.expectedTimeslotCount. I have kept both the values as 8400 timeslots (350 days of simulation). However, the games are stopping after approximately 1400 timeslots (60 days of simulation). @jecollins  Please let me know if I need to configure any other parameters to make the server run for one simulation year.

**Comment by erikkemperman** [comment]
Hi Sanjay,

Where are you specifying these values? Do the games with some warning or error in the logs?

**Comment by Sanjay-14BIT009** [comment]
Thanks for the reply. I am specifying these values in server-distributions's config/server.properties file. And, I don't see any error or warning at the end of the games.

**Comment by erikkemperman** [comment]
Yes, that should work... I will try to reproduce the issue -- can you tell me the precise version of server-distribution you are using, which java version you have, and the complete contents of your config/server.properties? Thanks!

**Comment by erikkemperman** [comment]
Oh, and just to check -- sorry if this is a silly question:
- You did specify "--confg config/server.properties" on the commandline?
- You did remove the "#" character from the beginning of the lines you edited?

**Comment by Sanjay-14BIT009** [comment]
Yes, I am specifying "--config config/server.properties" on the command line, and I have uncommented both the lines I mentioned above by removing "#".  Below are the configuration on my machine:

Java Version: openjdk version "11.0.11"
Server-distribution version: Power TAC distribution 1.9.0-SNAPSHOT

Content of config/server.properties (changed properies file to txt file to upload it here)
[server.txt](https://github.com/powertac/powertac-server/files/9028186/server.txt)
:

**Comment by erikkemperman** [comment]
Thanks. I've installed jdk 11 and am running a simulation with 4800 timeslots now -- I'll report what happens after it ends, or if it has passed 1800 by the end of my workday (1400 from server-main/server.properties defaults, which is what you were seeing I guess, plus 336 from the bootstrap).

But for what it's worth, the logs suggest that it is picking up my settings correcly:

```bash
≫ grep TimeslotCount log/powertac-sim-0.state       
2969:org.powertac.common.Competition::0::withMinimumTimeslotCount::4800
2969:org.powertac.common.Competition::0::withExpectedTimeslotCount::4800
2981:org.powertac.common.Competition::0::withBootstrapTimeslotCount::336
3359:org.powertac.common.Competition::0::withBootstrapTimeslotCount::336
```

My commandline:
```bash
≫  mvn -Pcli -Dexec.args="--sim --boot-data testboot.xml --brokers sample-broker --config config/server.properties"
```

**Comment by erikkemperman** [comment]
Well, it appears that it works on my machine -- the simulation is currently at timeslot 2100 and proceeding regularly. I'll leave it running and check back tonight.

**Comment by Sanjay-14BIT009** [comment]
I guess I figure out what is causing the problem. Actually, for my experiments, I need to use --random-seed argument of the server.  I suspect with --random-seed, long games were not happening as I was passing a previous state file as a random seed which contains state logs of a 2 month long game.  Without --random-seed argument, I am able to run year long games.

**Comment by erikkemperman** [comment]
Nice catch, glad you were able to resolve it! I don't know if this is the intended behaviour though, let's check that with @jecollins and @govertbuijs.

For what it's worth, my 4800 slot game finished without incident at timeslot 5160 (which is 4800 from server.properties plus 360 from boot (336 and 24 discarded).

**Comment by Sanjay-14BIT009** [comment]
Thank you for the help. I guess I have found a workaround to run long games with --random-seed. I will test it and report the outcome here. However, it would be helpful to know the standard way of running the long game with existing state files as a random seed @jecollins @govertbuijs.

**Comment by Sanjay-14BIT009** [comment]
Thank you for the reply. This is exactly what I did for running the long games.
