### ISSUE TITLE
Brokers not receiving server messages: server.CompetitionControlService: java.lang.NullPointerException

### ISSUE THREAD

**Issue by phipag** [powertac/powertac-server#1140]
There is an error in the server of the release candidate for version 1.9 which leads to brokers not receiving messages about information like market transactions and tariff transactions. 

Filtering the server trace file for "ERROR" messages leads to this output:
```
$ cat af89fd4a-fe14-400f-ba4c-58dc3165d3b9.trace | grep "ERROR"
3284 ERROR config.Configurator: no configurable property named minChunkSize on class org.powertac.customer.evcharger.EvCharger
58013 ERROR server.CompetitionControlService: java.lang.NullPointerException
69839 ERROR server.CompetitionControlService: java.lang.NullPointerException
81831 ERROR server.CompetitionControlService: java.lang.NullPointerException
93840 ERROR server.CompetitionControlService: java.lang.NullPointerException
105828 ERROR server.CompetitionControlService: java.lang.NullPointerException
```

This might be related to the most recent change in #1138.

**Comment by jecollins** [comment]
I tested the currently-deployed version of 1.9.0-SNAPSHOT, and it does not exhibit this problem. I suspect you have done a local build without doing a clean -- this can result in the AspecJ weaving not being applied to some classes.

**Comment by phipag** [comment]
@fmilkau Is that possible?

**Comment by jecollins** [comment]
I cannot reproduce this issue, and I can see the market and tariff transactions arriving in the broker using the current SNAPSHOT server.
