### ISSUE TITLE
Bootlog files naming convention changed

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#1142]
In a tournament setup (i.e. using the _--control_ param), the names of the boot trace and state changed.
This used to be _powertac-boot-\<game id\>.trace_
Now it seems to be changed to _powertac-config-\<game id\>.trace_
This messes up the tournament pipeline scripts, which expects the former.

**Comment by govertbuijs** [comment]
The Jenkins script adds the  _--control_ param to the command, which is a URL on the TS.
This URL presents the game params to the powertac-server.

**Comment by jecollins** [comment]
Govert says it's fixed.
