### ISSUE TITLE
Visualizer is out of date, not being maintained

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1155]
The current master branch does not build due to an apparent version mismatch somewhere in the visualizer. Unless we have a volunteer to take over and update the visualizer, we should remove it from the standard build.

**Comment by fmilkau** [comment]
Apparently there is a mismatch of OpenSSL versions between PhantomJS (OpenSSL 1) and newer Linux versions (OpenSSL 3).

For the time being, running Maven with the environmental variable `OPENSSL_CONF=/dev/null` seems to work as a quick fix. Please be aware that SSL deployment won't work this way. 

This StackOverflow thread provides some more details: https://stackoverflow.com/a/72679175

**Comment by jecollins** [comment]
Visualizer is no longer part of the standard config, and is not useful for research.
