### ISSUE TITLE
Bootstrap sessions cannot use weather data from an existing state log

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#1161]
For some reason, the ability to use weather data from an existing state log is supported only in sim sessions, not in boot sessions. One unfortunate consequence of this is that we cannot run boot sessions when the weather server in Rotterdam is not available. The only current alternative is to configure a local weather server, which is not a trivial process.

**Comment by WilliamTYH** [comment]
I believe this issue is closed with [05332ab](https://github.com/powertac/powertac-server/commit/05332ab629134cc72d9f85b80550ea530abfa2cd)
