### ISSUE TITLE
Repeating simulations using recorded random seeds

### ISSUE THREAD

**Issue by durieli** [powertac/powertac-server#667]
Hi,

I am trying to reproduce a run by loading random seeds with the flags:
--random-seeds
--weather-data

I see a discrepancy in the GenCo's ask amounts (mWh) starting the first submitted ask.
To reproduce:
1) disable randomness in the sample broker market manager (comment out the "random" related part)
2) run simulation with one sample broker
3) compare the broker's trace files or the server state file

Thanks,
Daniel

**Comment by jecollins** [comment]
I've tried a new approach: (1) generate a boot file, run a (short) sim without any external brokers -- we'll call it "base"; (2) run two new sims, using the same boot file, and using base.state for weather and random seeds. There is a very small difference in the second timeslot (362) in the last digit of a double. This slowly accumulates, and after two weeks the default broker's total is about .006% different in the two runs.

**Comment by jecollins** [comment]
We are not using strictfp declarations on classes, so it's possible to get different results for the same float/double operations across platforms. The strictfp declaration on a class or method restricts the use of floating-point hardware, reduces precision somewhat, and can dramatically slow the code. It's a modifier of class and method declarations, so using it would mean editing a large number of classes.

**Comment by govertbuijs** [comment]
I'm using the same strategy and found that we need to replace some HashMaps with LinkedHashMap for get fixed orders for for-loops. I'm trying to minimize the number of changes in the server modules.
The changes seem to be in accounting, auctioneer, default-broker and server-interface.
Not sure about common yet.
Also, we need changes to the sample broker, which means re-running old games is out of the question. And the current broker binaries are not suitable for perfect repeatability purposes.

Unfortunately things might change when we move to Java 8, as they changed some the implementation in Map, and that might break things that work atm with Java 7.

**Comment by jecollins** [comment]
I agree that there are probably places where order of evaluation might matter. But in my experiment, the first difference I saw between run 1 and run 2 was an extra digit in a double in one of the runs. I used diff after stripping off the msec: field, and I saw no ordering differences prior to that point.

**Comment by govertbuijs** [comment]
I'm almost there for the Java 7 version (the current master), things might change when we start using Java 8.
The last remaining problem is that the order of login of 2 sample-brokers changes the results considerably.

**Comment by govertbuijs** [comment]
With my forks of the modules below it's now possible to reproduce the same results, meaning that repeated runs ends with identical cash status for each (sample) broker.
Broker login order doesn't matter, this is needed for the experiment manager.
That still leaves us with the brokers from the binary repo, the current ones produce different end results. But i'm not sure if brokers build with these changes will generate repeatable results.

I've also added a configurable parameter to the sample broker, to fix its random seed.
Do we want this in the properties template, or shall i make an entry in the readme?

accounting
balancing-market
common
default-broker
factored-customer
household-customer
sample-broker
server-interface
server-main

**Comment by jecollins** [comment]
With Govert's recent changes, this appears to be finally fixed!
