### ISSUE TITLE
Tournament scheduler should be able to predict tournament duration

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#670]
The combination of variable-size games and random game-length makes it very hard for a game master to guess how long a given tournament setup will take to run. As a result, a conservative setup ends way too soon, and a more aggressive setup ends well after the promised end-date.

However, given the specifications for a tournament, it would be relatively easy to generate a distribution of tournament duration by running a number of instances in a discrete-event simulator. This would produce a histogram that could be presented to the scheduler.

**Comment by govertbuijs** [comment]
There's now a forecaster in the TS.

It can create an length estimation for a level (with parallel rounds). When the rounds start, the lengths will be copied to the DB (and subsequently used in the games).

It's also possible to forecast the length of the currently running rounds, in case rounds of multiple levels are scheduled or there were disruptions in the schedule.
