### ISSUE TITLE
Date fields not always clickable

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#800]
The 'From' and 'To' fields in the visualizer do not always respond to a click, making the editing of the dates impossible this way.

I'm not sure what's happening here, there doesn't seem to be a pattern. Clicking on the date just doesn't do anything. But after a few clicks or clicking somewhere else, it works as it's supposed to.

Chrome / Firefox on Linux.

**Comment by jecollins** [comment]
Old viz, won't fix.
