### ISSUE TITLE
Contact emails should be available through TS admin interface

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#806]
It should be possible to find email addresses through the admin interface for a variety of purposes, especially when encouraging teams to register, asking them to post their brokers, etc. Currently email addresses appear to be accessible for some "registered brokers" but not for others, and they are not available by username.

**Comment by govertbuijs** [comment]
Email addresses are available under 'Registered brokers', but the non-active brokers (i.e. not registered brokers) might be obscured.
'Show inactive' reveals all brokers, and the links are their email addresses.
