### ISSUE TITLE
Missing Artifact: ev-customer (maven) on server-main and visualizer

### ISSUE THREAD

**Issue by MunhozThiago** [powertac/powertac-server#809]
When downloading the whole project from Github (master) and importing with Maven, the packages "server-main" and "visualizer" give the following error on the pom.xml: 

"Missing artifact org.powertac: ev-customer: jar: 1.2.0-SNAPSHOT"

In fact, when looking into the directory, the .jar is really not there, but I do not know if it should be.

I've tested with different machines and different ways of downloading and importing but nothing helped. Downloading the module ev-customer and importing it to the workspace seems to solve the "missing artifact" problem, but start giving error on the following (server-main and ev-customer):

"The method configureNamedInstances(List<capture#3-of ?>) is undefined for the type Configurator"

    @Override
    public Collection<?> configureNamedInstances (List<?> instances)
    {
      return configurator.configureNamedInstances(instances);
    }

Obs: I'm using STS and tested in both Linux and Windows

**Comment by jecollins** [comment]
Yes, the ev-customer module is now needed. I thought I committed a new version of powertac-server that would suck it in. So there are two possibilities: (1) you have not updated that module, or (2) I failed to push it. I am on the road at the moment; I will check as soon as I can fire up my laptop.

I apologize for the confusion.

John




Sent from Samsung tablet

-------- Original message --------

**Comment by jecollins** [comment]
I believe this is now resolved. An updated powertac-server module has now been pushed. I am having some connectivity problems getting it tested, and I am almost out of battery. I would be grateful if someone else would test it.

**Comment by MunhozThiago** [comment]
Hello John,

First, thank you so much for your attention to this thread. I am a
researcher from the University of Porto, Portugal interested in
participating on the PowerTAC this year. My Ph.D. thesis is very related to
it and I think that this competition is a great opportunity to develop some
skills regarding the power distribution management in a dynamic market.

I have been working with multi-agent systems and have good knowledge in the
repast framework. If I manage to get this broker running, it would be a
great honor to help in that module too.

I will test the updated code by the night and see if everything is running
properly.

Best,

Thiago


*Thiago Reis Pedroso Munhoz Rúbio*
==============================
#Ph.D. Student in Informatics Engineering @FEUP
Contact: (+351) 932-840-816
Other: MunhozThiago
------------------------------------------------------------

2015-03-13 22:37 GMT+00:00 John Collins <notifications@github.com>:

**Comment by jecollins** [comment]
I was able to correct a couple of "non-tree" errors before my battery ran down. I believe it all works now.
