### ISSUE TITLE
Remove dependency between factored-customer and TariffMarketService

### ISSUE THREAD

**Issue by durieli** [powertac/powertac-server#812]
The following lines in TariffMarketService communicate with factored-customer:
registerNewSubscriptionRepoListener()
listener.updatedSubscriptionRepo()

The reason is that in order to shift consumption, factored-customer needs to see the updated subscriptions status, and subscriptions are updated only in TariffMarketService. The current solution notifies factored-customer about the update, which invokes shifting. John suggested an alternative solution of invoking shifting in the timeslot *following* subscription changes. One option is setting in flag in tariff evaluation, which will be checked in handleNewTimeslot() of factored-customer, and if set, factored-customer will compute shifting and unset the flag. Another possible solution is to send the subscription updates accross the code. 

The current solution seems to work well, so any change must be carefully tested to not break consistency.

**Comment by jecollins** [comment]
The factored-customer model now handles this case internally: a flag is set when tariffs are evaluated, and if the flag is set on activation, profiles are recomputed and the flag is cleared. Tested by inspecting logs.
