### ISSUE TITLE
Invalid values in ProfileRecommendation crashes the server

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#829]
ProfileRecommendation throws an error : Computed probability is NaN!
After that the game halts, although it's not clear if it's paused (SimPause is called) or ended (SimEnd is called just before SimPause).
The command doesn't finish.

It might have something to do with one of the brokers (SPOT) sending Infinite values.
But in other games it sent those values without causing the server to crash.

Command line out put : https://gist.githubusercontent.com/govertbuijs/6ae44581a6d80ab4edec/raw/e57baf1977cc5be3db0e2f500506638b5e862a66/gistfile1.txt

State file : http://wolf-08.fbk.eur.nl/log/powertac-sim-56.state
Trace file : http://wolf-08.fbk.eur.nl/log/powertac-sim-56.trace

**Comment by jecollins** [comment]
Added additional validity test to Rate to protect against Infinite values in a number of places, tested, pushed, deployed in 1.3.0-SNAPSHOT version.
