### ISSUE TITLE
Game log should contain unique game ID and pom version ID

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#834]
Right now, if you have a game log, you need to know its provenance to know the conditions under which it was generated. In particular, it's not easy to automatically digest a large number of games into a database without providing supplementary info about the competition in which it was run. 

I suggest a simple standardized way to name competitions, and putting the competition and game ID values, along with the version ID of the top-level pom.xml, into the Competition instance so it shows up in the log.

**Comment by jecollins** [comment]
POM version ID is now in both logs, and in the Competition instance so brokers can see it.

**Comment by jecollins** [comment]
Added command-line parameter game-id, which names the Competition and is a suffix in the boot and sim logfile names. Default behavior is unchanged. If the game-id is not given, then the game is called "game-n" where n is a session sequence number, needed if you run multiple sessions through the Visualizer.

**Comment by govertbuijs** [comment]
This is fixed, the TS sends a name based on tournament name and the game-number in that tournament.
