### ISSUE TITLE
Tariff evaluation takes expected regulation parameters, but does not include them in eval

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#855]
The data supplied by TariffEvaluator.initializeRegulationFactors() is not used anywhere that I can see. The battery model will need this; others would do a better job of evaluation if they had it.

**Comment by jecollins** [comment]
This appears to be fixed.

**Comment by jecollins** [comment]
The current scheme for adjusting evaluating tariffs with regulation rates does not work when the quantities in the given profile are zero - see Tariff.applyRegulationAdjustment(). Better to just adjust the kwh and then account for the regulation payments separately.

**Comment by erikkemperman** [comment]
hi John,

Probably related to your last comment: `powertac-common` currently fails its tests. If I remove the latest commit [7ae8d27dbc03c902f44cfb130357502a4ff4658a](https://github.com/powertac/common/commit/7ae8d27dbc03c902f44cfb130357502a4ff4658a) they pass.

The error is:
`TariffEvaluationHelperTest.testEstimateCostSimpleRateStorage2:419 correct result expected:<-28.92> but was:<-29.36>`

**Comment by jecollins** [comment]
Yes, I had hoped to fix that last night, but got too sleepy to concentrate. I should have a fix later today. Thanks for the temporary repair.

**Comment by jecollins** [comment]
Re-structured eval to avoid bogus "perKWh adjustment" scheme - now we simply adjust the profile by subtracting out expected curtailment, then apply the regulation prices separately based on customer's expected regulation quantities. Tests pass, evals look good in test game.
