### ISSUE TITLE
sample broker state log is empty

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#860]
It should not be empty, and it's not (yet) clear why it is empty. The file gets created with the correct name, but the size is always zero.

**Comment by erikkemperman** [comment]
This sounds suspiciously like the symptoms we saw earlier, which were due to misconfigured aspectj weaving

But then we got it working (end December, if memory serves)... Regression?

There was a mail exchange with subject "broker state logging", maybe there are clues in there.

**Comment by erikkemperman** [comment]
I just looked at my `sample-broker/log` directory; it looks as though it starts by creating an empty `broker.state` and `broker.trace` but then goes on to write to `broker1.state` and `broker1.trace` for some reason. Is that what you're seeing as well?

**Comment by jecollins** [comment]
When I ran the sample broker last night to test the latest deploy, it wrote its state log correctly. I'm going to close this issue; we can re-open if the problem recurs.
