### ISSUE TITLE
Several games in 2016 qual2 round got stuck in pause

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#874]
Is the server getting stuck in a loop?

**Comment by jecollins** [comment]
Working hypothesis is that this is a resource-exhaustion problem on the server side, possibly made much worse by similar problems in one of the brokers (SPOT).

**Comment by govertbuijs** [comment]
SPOT was kind enough to give me their faulty agent that was causing this problem.
With that i was able to reproduce the issue locally.

Somehow the server got stuck sending messages via JMS / ActiveMQ.
The upcoming upgrade of the ActiveMQ version fixes this problem.

**Comment by govertbuijs** [comment]
This is fixed with the new AMQ version.
