### ISSUE TITLE
Consider unifying servlet container across viz configurations

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#883]
Currently, we use Jetty for the embedded visualizer config, and Tomcat for the standalone (tournament) setup. Is this really necessary? Perhaps it's time to unify them and document the config setup better.

**Comment by jecollins** [comment]
The alternative is to abandon viz1. Eventually it will become too dependent on obsolete libraries to maintain. In other words, I consider this a low-priority task.

**Comment by erikkemperman** [comment]
Yes, my response to this issue was deliberately restricted to making sure the new visualizer uses only tomcat.

**Comment by erikkemperman** [comment]
@jecollins With the latest round of merges, I think this issue can be closed. Only Tomcat is now used.
