### ISSUE TITLE
Boot record should be bundled with logs in archived games

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#886]
We have run into a situation (the need to re-compute capacity charges for the 2016 finals) where data from the boot record is required to analyze games. If we want to automate this analysis across multiple games, we would have to find both the game log and the boot record. This is not impossible if the logs are in their original archived location, but much harder if the game logs were downloaded in the past without their boot records.

**Comment by govertbuijs** [comment]
What's the structure that we want to use?
Just put the 2 tars and the xml in a new tar?
Or unpack the tars to their own directory (log.boot and log.sim), and re-package them with the xml?

Also : keep them as tar or switch to zip (not sure what people use more).

**Comment by jecollins** [comment]
Rignt now, we have a log dir, containing 4 log files bundled as tar.gz, and a separate boot.xml. I would prefer to see all 5 files together; right now I'm unpacking the tar.gz and moving the boot record into the same dir, but I think it would be cleaner to have a structure like

boot.xml
log/
-- boot.state
-- boot.trace
-- sim.state
-- sim.trace

because then the same code can be used in a local env and against downloaded bundles. As long as the Windows folks can handle tar.gz, I would prefer to keep that format, because I already know how to write a script that will access those files directly without uncompressing/unpacking them. I'm not saying that's not possible with .zip, but that it would save me time, and I think it's simpler on Linux and Mac machines -- 2 out of 3. Has anyone asked for .zip?

**Comment by govertbuijs** [comment]
I've repackaged the xml into the tarball for the 2016 finals.
http://ts.powertac.org/log_archive/finals_2016_06/

Do we need this for previous competitions as well?

**Comment by jecollins** [comment]
Thanks. If you have a script that does it, I would wait until you get a request. For the capacity-charge correction, I wrote a script that retrieved the boot records and sim logs separately. It was while getting that to work correctly that I wrote up the issue. I'm sure this won't be the last time we need to examine boot records and logs together, but it's not a common requirement.

**Comment by jecollins** [comment]
I have never seen a need to have the boot logs for analysis purposes, but they could be very important for some types of analysis, especially when trying to understand potential software defects. Here's an alternative directory structure that combines boot logs, the boot record, and the sim logs:
```
boot.xml
log/
-- sim.state
-- sim.trace
-- init.state
-- init.trace
boot-log/
-- boot.state
-- boot.trace
-- init.state
-- init.trace
```
This way, it would be easy for automated tools to ignore the boot log data, without needing to keep track of it separately as we are now.  The boot logs are relatively small compared to the sim logs, and so this should not be an excessive burden.

**Comment by jecollins** [comment]
I believe this is now implemented in the TS. Govert, can you confirm?

**Comment by govertbuijs** [comment]
It's not implemented in the TS but in an after-tournament script.

The filenames for the sim and boot are now both _game_name.state_ (same for trace).
Do we want them simplified to _sim.state_?

**Comment by jecollins** [comment]
I think we should leave the filenames alone for this year, so we don't create inconsistency across tournament rounds.

**Comment by jecollins** [comment]
At this point, you can download from the TS while it's running, and you get just the logs. The boot records must be downloaded separately. At some point (after a tournament is over?) there's a process that re-bundles them and posts them somewhere else. This system is confusing at best.

**Comment by govertbuijs** [comment]
The TS now bundles the log files, bootlog files and boot xml.
