### ISSUE TITLE
AspectJ setup in common and dependent modules

### ISSUE THREAD

**Issue by erikkemperman** [powertac/powertac-server#892]
I noticed that the AspectJ maven plugin (and some others) are wrapped in an `<pluginManagement>` tag, which seems incorrect to me. It means that these plugins are not being run during build, and since common is not the parent of any other module I don't think it makes sense to have this tag at all...

This needs further investigation, including how other modules are currently using common -- they need aspect weaving to function. Which they do, so it would appear that currently weaving is done on the receiving end of the common dependency, but this was not a deliberate design choice.

**Comment by erikkemperman** [comment]
Addendum: maybe it makes sense, while looking into this, to also revisit the maven-sources-plugin and maven-javadoc-plugin configuration in the same `<pluginManagement>` tag. Their setup in common differs from the same plugins' setup in other modules, c.f. broker-core.

Personally I think sources should always be attached when building (this should pre-empt the errors we see currently when building server modules against a locally built common) and javadoc only when releasing.

**Comment by jecollins** [comment]
Interesting observation: with the <pluginManagement> wrapper, the output of mvn clean install does not include any indication of the AspectJ compiler; without the wrapper, we see the AspectJ compiler running in the build and in the test-build. However, the sizes of the jar files in the powertac.common package are unchanged, with out exception: TariffEvaluationHelper gets a bit smaller when AspectJ runs. TEH has no aspects, and no behavior that should interact with aspects -- it does not create @Domain instances, and it does not change state of any @Domain instances. It's not the only class in powertac.common that interacts with other classes -- Tariff interacts with Rate instances, for example.

**Comment by jecollins** [comment]
One more observation: remove the 'phase' clause from the maven-source-plugin config, and the source jar gets installed by default.

**Comment by erikkemperman** [comment]
Yes, as I reported, the aspectj plugin does not run when encapsulated in pluginManagement (nor do the others). 

I read that the source plugin can be activated by binding to a phase, indeed. The docs recommend `validate`.

**Comment by erikkemperman** [comment]
@jecollins This one also is resolved now, I think.
