### ISSUE TITLE
Error in Viz2 handling incoming Tariff TX

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#894]
The message is "Incoming spec 200000555 not matched in repo". The message is generated on line 235 of service_ptac/MessageHandler.java. This is the TariffTransaction handler. The only possible tariff transaction for this error is the PUBLISH transaction that occurs immediately after the tariff arrives and is processed, and before the tariff status is changed to OFFERED.

**Comment by jecollins** [comment]
In TariffMarketService.handleMessage(TariffSpecification) the new tariff is added to the repo before the PUBLISH tx is generated.

**Comment by erikkemperman** [comment]
If I remember correctly, my feeling at the time that this particular error can be safely suppressed in the visualizer, it looks to me like that's the only place this kind of out-of-order messages would happen, as the server selectively filters messages to the viz.

**Comment by erikkemperman** [comment]
Do you agree the viz2 can safely ignore this error? If so I will make it so and we can close this issue.

**Comment by jecollins** [comment]
Yes, we can safely ignore this error.
