### ISSUE TITLE
Viz2 game-replay option should not require copying state log into user file space

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#901]
At this point, in order to view an old game, it seems to be necessary to copy the state log into the viz2 files tree. These files are quite large. Worse, it's not possible to write a script that downloads and uncompresses logs from a website into that directory, because the viz2 database needs to be involved in moving them into place.

It would be far better to provide a file-picker, and to allow selection of a compressed game file. Better yet, allow direct web access. Ideally, the Tournament Manager or some other well-known web address could host a REST interface that supports navigation to individual games, which would be downloaded and uncompressed without further user intervention.

**Comment by jecollins** [comment]
In addition, my first attempt to upload a game state file from the 2016 finals failed with a "file too large" error.

**Comment by erikkemperman** [comment]
The file limit can be configured in the yml config.

I think we can get the viz to sync its db from the file system on startup, or maybe repeatedly at some fixed interval, if you expect people will want to drop in files manually... 

But if I understand your scenario correctly, it might be more convenient to allow the user to provide an external log URL, in the viz gui, e.g. besides the upload button?

**Comment by jecollins** [comment]
Even better to provide for navigation of datasets maintained by us, the organizers, or by anyone implementing the same REST interface, which we could provide as part of the Experiment Manager, as well as the Tournament Manager. Choose the year, the competition, perhaps see the list of games with summary stats (brokers, results), and choose a game.

**Comment by erikkemperman** [comment]
I see. Yes, that'd be very nice indeed. A lot of work though. If we think it's worthwile I think I could implement a simple URL box quite quickly, as a stopgap until the pretty feature is done? It'd be slightly less inconvenient, it seems to me, than downloading a state log to disk and then uploading it into the viz2, which is currently the path to replay external games.

**Comment by govertbuijs** [comment]
I don't think we should connect this to either the TS or the ES.
The setup of those systems is already too complex, tying them to the visualizer makes things more complicated. 
Maybe even more important: the information about past tournaments isn't in the TS anymore.

**Comment by jecollins** [comment]
Perhaps there's an existing package that provides for archiving of datasets and a REST navigation interface? Would that be similar to the way Maven Central works?

**Comment by jecollins** [comment]
As a temporary measure, it would be very nice to just have the option to bring up a file-picker for replaying. I often download complete tournament datasets and I have a script (it's a python script in powertac-tools) that unpacks all of them and runs them through analysis scripts. It would be very helpful to just look at games with the viz without needing another step. I guess it would be easy enough to symlink them into the files space, but incredibly tedious to upload them individually, which makes copies rather than symlinks.

**Comment by jecollins** [comment]
How about [Archivematica](https://www.archivematica.org/en/)?

**Comment by erikkemperman** [comment]
If the visualizer were to sync its database every so often with what's on disk, symlinks would work. And, unless I understand what you mean by "file-picker", those would then be pretty easy to navigate with the existing GUI for selecting a state log to replay?

I'll take a look at Archivematica when I have more time, but I think the above suggestion might give a  decent improvement for not too much effort?

**Comment by jecollins** [comment]
It would be a big improvement, as long as "every so often" is at least as often as I go looking for a log file. I guess state log files can be "weather" files, so there could be some confusion between "state" and "weather" files. Also, there should be an easy way to "clean up" if I want to look at a different tournament. There are hundreds of games in a tournament. After I've looked at 2-3 tournaments, I could have close to 1000 state logs to search through. Better to allow a directory hierarchy, which is what you get if you download games from the web and unpack them. Each bundle turns into a directory when you unpack them. Even better to permit "indexing" of external directories that are not under the "files" tree.

**Comment by erikkemperman** [comment]
Well, all the viz uses to replay a game is the state log. It assumes all relevant data is in there. So as long as it can find that reliably within such a bundle I guess it's all right.

The way I imagine syncing would work should also handle the case of files disappearing from the filesystem. So if that's in place, I don't think we'd need a gui to tidy up?

Probably syncing would happen at some fixed interval, but forcibly upon startup and when the pop up to select a state log is summoned?

**Comment by erikkemperman** [comment]
Also, but perhaps a separate issue, I suppose it would be good if the viz can de/compress log files, including the ones it generates itself, to reduce footprint.

**Comment by erikkemperman** [comment]
the filesystem-sync feature discussed here was merged into master along with the recent upgrade PR. Should we close this issue, or wait until it is part of an actual release?

**Comment by jecollins** [comment]
When I ask to re-play a game, it brings up an interface that only includes files that are already in my local files/admin/... tree. No file picker. If I use the files tab to access tournament games, I must first (1) download the compressed file from the archive, (2) uncompress the tar.gz, giving me a directory, (3) use the file-picker to navigate to that directory and pick out the state log. The state log is then in a big heap of numbered files, and I lose the correspondence between the file and tournament and tournament id for that game (because the name of the state log file does not correspond to the name of the compressed file). At the very least, I want to be able to pick the tar.gz and not have to copy it, and I don't want to have to clean up the uncompressed file afterward. Ideally I could just give it a URL.

**Comment by erikkemperman** [comment]
Perhaps I misunderstood earlier discussion and/or this last comment... But the idea of the sync feature currently in master to use shell or operating system tools to just put the state logs you want to replay in files/user/log. No need to use upload, after a couple of seconds it should appear in the dialog for choosing state log to replay.

This seems to me a reasonable (first) improvement to this inconvenience -- I don't think it's a great idea, to be honest, to bake in all kinds of assumptions on how tar files from e.g. tournament scheduler are layed out, or replicate within the viz a bunch of functions e.g. decompress) for which we have tools readily available.

Does this make sense?

**Comment by jecollins** [comment]
First, opening a file that's inside a tar.gz is not that hard in Java, and opening a tar.gz from a URL is also not a big problem. But even if we give up (at least for now) on the URL approach, I would very much like two features: (1) ability to keep file sets that come from individual tournaments or experiments apart in a directory structure, and (2) ability to read directly from the compressed logs.

I guess perhaps what I am completely confused about is the apparent centrality of the "sync" function and the associated database. I can see the drawbacks, but I cannot see what we gain with this scheme. Why can I not just give it an arbitrary file path or a URL? Filesystems were invented for a reason and are well-supported by our tools, and a tar.gz is essentially a filesystem extension.

**Comment by erikkemperman** [comment]
Perhaps the misunderstanding here is about the term "file-picker"?

The dialog that you get when uploading a file is built into the browser and can _not_, for good reasons, be used to point the server to a path on the user's disk. It can copy the file itself to the server's disk and get its basename, but that's it.

Even though we probably expect the "user disk" and "server disk" to be the same thing in typical usage of the viz, the browser does not (and should not).

My attempt at making this a bit less cumbersome, the sync function, tries to remove some of the annoyance of having to use the upload feature for files already on the right disk just to make the db aware of it. So now we can use extant tools to copy or symlink natively, in scenarios where the user has control over the server's fs.

I'm a bit confused by your reaction though, it seems to me this sync function is pretty much what we arrived at during earlier discussion in this very thread. So what am I missing?

**Comment by jecollins** [comment]
Sorry, Erik. The sync function turns an unusable research tool into a usable one, but not for most of the use cases a researcher would want. I believe the problem is that for a researcher, the viz is a local (desktop) tool, not a web tool. I don't see why you would ever want the replay option on a hosted version of the viz; it should probably be disabled in a hosted setup. As a desktop tool, a researcher would typically want to use it to explore data across tournaments and experiments. There can be hundreds of games in a single tournament, and an experiment might cover tens of treatments, each with 20-100 games.

One way to make this a less dire problem would be to fix the naming of individual logfiles so they preserve the tournament/experiment name, and to update the tournament scheduler or experiment manager so the compressed bundles have names that match the names of the contained files. Right now that correspondence is broken, so once you unpack the compressed archive, you lose track of where the data came from.

Perhaps there's another way to look at this issue, and perhaps I don't fully understand what the capabilities of a hosted viz might include. Maybe we should not think of the viz as a desktop tool at all, or perhaps there should be desktop and hosted versions. If 10 people log into a single hosted viz, I suppose they could each use it to inspect different games, right? If so, perhaps it would make sense to host an instance for each tournament, with all the games in the tournament pre-loaded into the "shared" space. That way, nobody would have to download or extract the logfiles locally until they needed to use other analysis tools on them. One of the students at Minnesota did something like this for TAC-SCM data; he built a hosted webapp that had access to all the tournament data from several years, and a large set of analysis tools he had built that would generate and serve plots. Some of the tools could aggregate data over multiple games based on fairly arbitrary selection criteria (using SQL).

**Comment by erikkemperman** [comment]
Yes, in research mode we'd like to think of the viz as a desktop tool. It's just that because of some overlap with tournament mode it also uses a browser to present GUI. I think that choice, inherited from viz1, is essentially imposing limits on facilitating the kind of scenario you outline. I'll think about this some more...

**Comment by erikkemperman** [comment]
I've made a PR that would allow us to replay from remote (and optionally compressed/archived) locations: https://github.com/powertac/visualizer2/pull/22 

Note, in the case of archives, it just looks for the "first" archive entry that's not a directory, has a name ending with `.state` and not ending with `init.state`. That should work with the tarballs produced by the Tournament Scheduler, but not arbitrarily archived state logs.

**Comment by jecollins** [comment]
Very nice solution. Tested with local archives and with remote URLs.
