### ISSUE TITLE
Excess state logging in factored-customer

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#902]
Now that factored-customer is getting the aop build step, there are huge numbers of obscure entries in the state log, and it's not clear how they would be used. Perhaps some cleanup is needed.

**Comment by jecollins** [comment]
I found no cases where the state logging in factored-customer added value to the log. All annotations removed.

**Comment by erikkemperman** [comment]
Might as well remove the AspectJ configuration from factored-customer's pom as well, then?
