### ISSUE TITLE
Re modularize to simplify build process

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#903]
There are now 8 different modules that must be built to do a full install or deploy, and many more to do a release. This could probably be reduced to three in both case, as follows:

- Move powertac-parent, powertac-aop, common, and broker-core into a multi-submodule structure, perhaps called powertac-core.
- Make server-master (perhaps renamed to server-parent), logtool-core, and visualizer2 submodules of powertac-server.
- Remove webapp-dependencies by integrating it into visualizer. I don't believe there are any other dependencies on that pom.

**Comment by erikkemperman** [comment]
I like this idea, a lot. So +1, as they say!

**Comment by jecollins** [comment]
Status update:

- Created new module powertac-core to wrap powertac-parent, powertac-aop, common. This builds correctly in a clean environment.
- Unable to build powertac-server the same way -- server-parent does not resolve. All the advice I could find was that the aggregate project (powertac-server) needed to also be the parent.
- Made powertac-server be the parent for server modules. It builds, but also attempts to generate javadocs for all the individual modules as well as the top-level javadoc. Probably we need to disable the automatic javadoc generation for powertac-server.

**Comment by jecollins** [comment]
Tested version pushed to github. No changes needed in powertac-parent, powertac-aop, common -- all these are now submodules of powertac-core. The bundle module powertac-server now contains all server modules. The functionality of server-master is now in powertac-server, and the functionality of webapp-dependencies is now in visualizer. The logtool-core and visualizer2 modules are now submodules of powertac server. These changes to powertac-server and all its submodules are currently in github under the clean-build branch.

**Comment by erikkemperman** [comment]
Sounds good! I'll try to find some time to try it out this week.

**Comment by erikkemperman** [comment]
I've played around with this for a bit. Mostly it just works, I've run into a few little things and made PRs for those. The only significant change I don't really understand is why the position of the "parent" module within a multi-module maven project's local directory structure is different for powertac-core and powertac-visualizer?

In powertac-core, the parent (powertac-parent) is a sibling directory of the other modules (broker-core, common, powertac-aop). This is similar to how it used to work for powertac-server. But there it has changed, server-master has been renamed to server-parent but doesn't really do anything anymore, as far as I see?), and the guts of its pom.xml have moved into the pom in root directory of powertac-server.

Is there a particular reason for this? I have no real preference for one style over the other of positioning the parents within a multi-module structure, but think it might be convenient to use the same in both powertac-core and powertac-server.

**Comment by jecollins** [comment]
What you suggest is what I tried first. But there are two reasons why I settled on this approach:

1. powertac-parent and server-parent play different roles in the system. powertac-parent is parent of all modules in the system. In other words, it needs to be accessible OUTSIDE the powertac-core aggregate module. The parent of all the server modules, on the other hand, is used only INSIDE its aggregate module.
2. All my attempts to get the server to build with server-parent failed. After some search, I found the cleanest explanation in a [stackoverflow post](http://stackoverflow.com/questions/38277084/including-parent-project-in-a-maven-reactor-build). It seems that dependencies on pom-type modules are handled differently than dependencies on jar-type modules.

At this point I cannot explain why one works and the other does not, but reason 1 suggests we are lucky that powertac-parent builds separately, because otherwise we would have to use powertac-core as parent in other modules, which seems ugly. Better to keep it separate in that case.

server-parent can be deleted.

**Comment by erikkemperman** [comment]
I don't really understand that explanation on stackoverflow, but fair enough.

**Comment by jecollins** [comment]
I believe this work is complete. Both aggregate modules clone properly with git clone --recursive. Both aggregates build properly with mvn clean install (or deploy) into a clean maven repo. Both are deployed, and the system runs correctly from server-distribution with a clean local maven repo. The [instructions in the github wiki](https://github.com/powertac/powertac-server/wiki/Getting-started) have been updated.
