### ISSUE TITLE
Visualizer2 gets out of sync with game

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#904]
Occasionally, the new visualizer thinks a game is finished when it's still running. To reproduce (at some non-zero probability), specify a game in the games tab, including a broker. Start the broker; when you look back at the games tab, it says finished, but the sim and broker are still working and the game completes normally.

**Comment by jecollins** [comment]
I set things up so I could watch what happens. Pretty much immediately after hitting the start game button, it goes to "finished" and prompts for another game. In the meantime it actually has started the sim, which is waiting for logins. Also, I believe that each time this happens, an interesting pattern shows up in the console. Here are two examples:

presentedToken=xeR2yfc3fROK/qCX69abZw== / tokenValue=xeR2yfc3fROK/qCX69abZw==

presentedToken=yg0ge+COxRArrTt9XvXbqQ== / tokenValue=yg0ge+COxRArrTt9XvXbqQ==

**Comment by erikkemperman** [comment]
Hm, that looks like it messes up session handling. But it shouldn't make a difference, a running game is "above" the session level. 

If it's convenient, I'd be interested to learn what happens if, in this situation, you open a new browser in incognito mode. Or log out and refresh the Graphs tab?

**Comment by jecollins** [comment]
The situation showed up again this evening. I closed the browser window, opened a new one on the running system, and it shows a game running with the correct data.

**Comment by erikkemperman** [comment]
Just opened [PR #14](https://github.com/powertac/visualizer2/pull/14) on visualizer2 which fixes the reconnect logic. An attempt by Jurica to handle this was in place already, but was attaching to a non-existing event callback in the STOMP websocket library.

The new logic does a (staggered) exponential backoff reconnect, starting at 1 second and doubling at each failed attempt to a maximum of 32 seconds. Maybe these intervals could be improved upon, but qualitatively I think this fixes the main problem.

**Comment by erikkemperman** [comment]
For posterity, the problem occurs when the server is re-started but the client is not refreshed (F5). In that situation the frontend is only partially functional -- it allows form submissions (e.g. to start games) but is not receiving game updates via its websocket subscription.

**Comment by jecollins** [comment]
This appears to be fixed. Thanks, Erik.

**Comment by erikkemperman** [comment]
Glad we've got this sorted out!
