### ISSUE TITLE
Sample Broker doesn't compile

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#912]
Changing mockito-all to mockito-core in commit ee21d707601a50a67b8559e16254e88d01949f30
seems to break the sample broker on a clean .m2 repo.

**Comment by erikkemperman** [comment]
I'll take a look.

I was confused by this nabble message though, it says the sample-broker doesn't compile but includes the output of failing to build scengen?

http://power-tac-developers.975333.n3.nabble.com/Error-While-building-and-running-the-sample-broker-tp4026492.html

We should revisit all modules I guess, some appear outdated. This scengen for instance is at 1.1.0-SNAPSHOT and still refers to server-master.

**Comment by erikkemperman** [comment]
This is due to the post-upgrade versions of powertac-parent (and others that would be pulled in by attempting to compile sample-broker against an empty .m2) not being published on sonatype. So it gets the previous powertac-parent, which doesn't yet have mockito-core in its dependencyManagement.

We can close this when the latest snapshots are on sonatype.

**Comment by jecollins** [comment]
Right. I have not yet deployed the version upgrade, and the latest sample-broker source depends on the upgrade. I was hoping to have viz2 working first. I guess the answer is that this is the risk one takes occasionally from working on the bleeding edge.

**Comment by erikkemperman** [comment]
But is there any other way of "Getting Started" than getting the sample-broker from git?

**Comment by jecollins** [comment]
Yes, release packages are always available. But if you want the latest development version, the only way is to download the master branch.

**Comment by jecollins** [comment]
I have completed the new deployment, and sample-broker now builds with an empty local maven repo.
