### ISSUE TITLE
State log entries are written to both the trace log and the state log

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#913]
I am not sure when this started, but it must be in the last couple of weeks. The log files are already extremely large, and this is roughly doubling the size of the trace log.

**Comment by jecollins** [comment]
This may be happening because the acknowledgement of a new tariff is sent to the broker before the spec is added to the TariffRepo, and before the Tariff object is created. Why does the viz need to see the spec in the repo at this point?

**Comment by jecollins** [comment]
The problem occurs when running with mvn -Pweb2, not with mvn -Pcli.

**Comment by erikkemperman** [comment]
Fixed in https://github.com/powertac/visualizer2/commit/e0410e9e6dfa1e7aa89036d07c1e48d1d2852484
