### ISSUE TITLE
viz2 game-overwrite function fails to write sim log

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#914]
When running a game through the viz2 GUI, one of the options is to re-use the name of a game, which should result in replacement of logfiles. This seems to work for boot logs, but for sim logs the original file by the same name is deleted and no new log is written.

**Comment by erikkemperman** [comment]
I hope this was fixed by https://github.com/powertac/visualizer2/pull/21 -- if you can confirm, this issue can be closed.

**Comment by jecollins** [comment]
Agree. I tested it.
