### ISSUE TITLE
factored-customer.jar 1.4.1 not being resolved in maven central

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#919]
1.4.1 release works if run with `mvn -Pweb2`. However, it fails to find factored-customer.jar when run with `mvn -Pcli`. The 1.4.1 version of factored-customer appears to be installed correctly on [maven central](http://repo1.maven.org/maven2/org/powertac/factored-customer/1.4.1/), along with the other modules. 

Here is the error message:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Power TAC distribution 1.4.1
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/powertac/factored-customer/1.4.1/factored-customer-1.4.1.pom
Downloading: https://repo.maven.apache.org/maven2/org/powertac/factored-customer/1.4.1/factored-customer-1.4.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/powertac/factored-customer/1.4.1/factored-customer-1.4.1.pom (2 KB at 4.7 KB/sec)
[WARNING] The POM for org.powertac:customer-models:jar:1.4.1 is missing, no dependency information available
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/powertac/factored-customer/1.4.1/factored-customer-1.4.1.jar
Downloading: https://repo.maven.apache.org/maven2/org/powertac/factored-customer/1.4.1/factored-customer-1.4.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.131 s
[INFO] Finished at: 2017-03-21T11:46:58-07:00
[INFO] Final Memory: 14M/163M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project server-distribution: Could not resolve dependencies for project org.powertac:server-distribution:pom:1.4.1: Could not find artifact org.powertac:factored-customer:jar:1.4.1 in sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```

Note that there is also a complaint about customer-models, and that it did download the pom.xml from maven central.

**Comment by erikkemperman** [comment]
I think factored-customer is _not_ deployed correctly in maven central. The 1.4.1 directory has an entry (link) for the jar:
http://central.maven.org/maven2/org/powertac/factored-customer/1.4.1/
... but it isn't actually there:
http://central.maven.org/maven2/org/powertac/factored-customer/1.4.1/factored-customer-1.4.1.jar
There might be other modules with the same issue, I didn't check, but factored-customer is the first and mentioned in the error.

**Comment by jecollins** [comment]
This turns out to be a [problem on the Sonatype end](https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-29021?filter=allopenissues).

**Comment by erikkemperman** [comment]
Interesting, so their CDN was caching 404 responses after the jar had actually been published... Not the first thing I'd have thought of.

**Comment by jecollins** [comment]
Perhaps, or possibly there's a race condition somewhere. For example, they
push out the updated content, and then retrieve it, and in this case they
tried to retrieve it too soon? But in that case they could have easily
spotted it. In any case, a major glitch for them. This is the first time
I've seen an obvious flaw in their process.

Cheers -

John
