### ISSUE TITLE
Sample broker doesn't run from jar

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#920]
- Clean local .m2
- mvn clean package

$ java -jar target/sample-broker-1.4.1.jar
no main manifest attribute, in target/sample-broker-1.4.1.jar

exec:exec works as expected

**Comment by govertbuijs** [comment]
It seems that ${maven-exec.class} isn't inherited from powertac-parent.
Hardcoding works.

**Comment by govertbuijs** [comment]
Quick fix for now.

**Comment by erikkemperman** [comment]
Huh. Never even tried running it from jar...

**Comment by jecollins** [comment]
We never intended the broker to run as a jar.

**Comment by govertbuijs** [comment]
It's in the README :

https://github.com/powertac/sample-broker#prepare-an-executable-jar
