### ISSUE TITLE
NullPointerException in visualizer (v1)

### ISSUE THREAD

**Issue by erikkemperman** [powertac/powertac-server#923]
As reported by Imbhat on Nabble, an NPE occurs in the old visualizer when graphs in the TariffMarket tab are requested.

It turns out this NPE happens on line 96 of TariffMarketBean:
https://github.com/powertac/powertac-server/blob/master/visualizer/src/main/java/org/powertac/visualizer/user/TariffMarketBean.java#L96

Specifically, it gets TariffData with PowerType `STORAGE`, but then it can't match that type in the HashMap it is populating because this type was commented out in this commit:
https://github.com/powertac/powertac-server/commit/b46e975b5fa6acc2c91aba1dd26283b94f782704#diff-0a157839309df88c3580e53838b9bacdR73

I'm not sure how to resolve this, and figured I'd just ask before spending a lot of time tracking this down if this rings any bells? The superficial fix would be simply to check for presence of the type at hand in the HashMap, and skip the TariffData if not, but that might just be suppressing symptoms of a deeper problem.

**Comment by jecollins** [comment]
I suspect that change commenting out STORAGE was from a time when we were trying to make all the PowerTypes be either a subtype of CONSUMPTION or PRODUCTION. Should be fine to restore it.
