### ISSUE TITLE
Many logtool-examples classes use an old name for DOR

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#928]
The logtool.xml file maps logtool-core classes to names for lookup through the Spring app context. At one time, the DomainObjectReader was mapped to "reader", but this violates a common Spring convention and was causing confusion. As a result, it was re-mapped to "domainObjectReader", but some of the example classes did not get updated. That needs to be fixed.

**Comment by mansarin** [comment]
So this:
dor = (DomainObjectReader) getBean("reader");
Needs to be replaced with this:
dor = (DomainObjectReader) getBean("domainObjectReader");

?

Also, is it necessary to specify class? Some examples specify class (or specify the function: dor = (DomainObjectReader) SpringApplicationContext.getBean("reader"); ) while others don't.

**Comment by jecollins** [comment]
Yes, but there is a better way that does not require a reference to the DomainObjectReader. I am almost finished with all of them. Half are already pushed.

**Comment by jecollins** [comment]
See https://github.com/powertac/powertac-tools/commit/2ee6f36f72b9cd5221c89b62ce74a6834cf9e122 for examples.

**Comment by jecollins** [comment]
All the examples have been updated to work correctly with the latest (1.4.2-SNAPSHOT) logtool-core.

**Comment by mansarin** [comment]
Thanks. If I've understood correctly, there's a new handleMessage class which makes DomainObjectReader moot.

**Comment by jecollins** [comment]
DomainObjectReader is an essential part of logtool-core, but the connection between incoming messages from the state log and their associated behaviors is now made at runtime, by reflection. See LogtoolContext.registerMessageHandlers(). Incoming messages are then dispatched by matching the message type with the available handlers in DomainObjectReader.dispatchMessageListeners(). The server and sample broker have been working this way for a while; I just adapted it to the logtool environment, without removing the original explicit registration scheme.
