### ISSUE TITLE
Common Configurator can't handle empty values for instances

### ISSUE THREAD

**Issue by govertbuijs** [powertac/powertac-server#933]
When the value for _pkg.class.instances_ is left empty, Apache Commons interprets that as an empty string. 
Therefor its not possible to configure no instances of a model.

**Comment by govertbuijs** [comment]
This also might cause problems for 'normal' configurable parameters.

**Comment by jecollins** [comment]
This looks like a complete fix. Is there any reason not to close it?

**Comment by govertbuijs** [comment]
The fix is only for the instance-configuration.
Are there other situations where an empty value shouldn't be interpreted as a empty string?

**Comment by jecollins** [comment]
I cannot think of any other cases where we would want to accept an empty string.
