### ISSUE TITLE
Anomalous high prices for positive imbalance in 2017 finals.

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#941]
COLDPower17 is running very large positive imbalances in the finals games and appears to be paid way too much for them. It is able to win games with very little retail activity. Here's an example from game 6, TS 415:
```
464691 INFO  AccountingService: market position for COLDPower17: 192.17391304347825
464691 INFO  AccountingService: net load for COLDPower17: -1888.29
464691 INFO  BalancingMarketService: market balance for COLDPower17: 190285.62304347823

464691 INFO  BalancingMarketService: balancing prices: pPlus=0.4854888241047859, pMinus=-0.020498593946362602
464691 INFO  balancemkt.SettlementProcessor: totalImbalance=143799.0730995576

464693:org.powertac.common.BalancingTransaction::147072::new::4700::415::190285.62304347823::23462.308497225105

464693 INFO  balancemkt.SettlementProcessor: DU static settlement <broker(p2,p1)>: default broker(-0.0,0.0) ewiBroker(-0.0,45.92233661090569) SPOT(-0.0,6.477982543719979) maxon17(148.62144565530127,-4035.950098595956) fimtac(-0.0,0.217119813740861) VidyutVanika(-0.0,-1714.6044159894152) COLDPower17(-0.0,23462.308497225105) AgentUDE(-0.0,-33.876806647340324)
464693 INFO  balancemkt.SettlementProcessor: DU budget: rm cost = -17581.87316930546, broker cost = 17879.116060616063
```
So COLDPower17 got paid 23462 for its positive imbalance of 190286 kWh. That's .123/kWh, or 123/MWh. It looks like the slope on pMinus might be messed up.

**Comment by jecollins** [comment]
Running a short game with Sample and a mod called Surplus that always buys 20x what it needs in the wholesale market. Surplus wins big.

**Comment by jecollins** [comment]
The current value of balancemkt.balancingMarketService.pMinusPrime is negative. It should be positive. Changing the sign and running the Surplus agent means that Surplus is now having to pay for its excess surplus.

**Comment by erikkemperman** [comment]
For what it's worth: been negative for a long time now, and it looks to have been a deliberate change at the time?
https://github.com/powertac/powertac-server/commit/aaa7cac6e9263a2140284daabbb51c8fb1b8c95d#diff-528acfd8a5a0c4f9532a571defac8f47R153

**Comment by erikkemperman** [comment]
Never mind that last comment, I had not yet seen the emails regarding this problem. I guess this could (only) have surfaced recently, with the consolidation of config items in a single place? I.e., perhaps the default I linked above was previously being overwritten to a positive value in a now-deleted properties file?

**Comment by jecollins** [comment]
The problem is not the configuration. It is in the calculation of the p1 value for brokers with positive imbalance in cases where overall imbalance requires down-regulation. For up-regulation, a positive value was being multiplied by the sign of of the "exercisedCapacity" in the dummy balancing order that represents grid balancing resources. This is positive in an up-regulation situation. For down-regulation, the cost (positive only in case the down-regulation is small) is multiplied by the sign of the negative exercised capacity. The multiplication by this sign cancels out the correct negative cost value in this case, and charges brokers when it should be paying them for small positive imbalance values. The fix was to remove the multiplication by the sign of the exercisedCapacity and just return the computed cost.
