### ISSUE TITLE
Experiment Scheduler games are run for 2098 timeslots

### ISSUE THREAD

**Issue by mansarin** [powertac/powertac-server#943]
Unlike competition games, which normally run for around 1400 timeslots, game lengths for experiment scheduler games are 2098 timeslots. Example: all games in the Test_Mohammad_ experiment set. However, upon checking the default parameters in the experiment scheduler's Studies page, the defaults are:

common_competition_minimumTimeslotCount | 1400
common_competition_expectedTimeslotCount | 1440

So game lengths should be similar to competitive games. What might the problem be here?

**Comment by govertbuijs** [comment]
Game lengths are calculated once per study and set for all experiments and games in that study.
They are calculated the same way as in the TS, and sometimes very long games happen.
