### ISSUE TITLE
Regulation parameters for tariff eval are not set in most customer models.

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#944]
In order to properly evaluate tariffs with RegulationRates, customers need to initialize three parameters,  expCurtail, expDischarge and expDown. Currently the only models that initialize these parameters are ColdStorage, LiftTruck, and Battery. All models capable of regulation or curtailment should initialize these parameters.

**Comment by Andyccs** [comment]
Hi. I was trying to set very unreasonable regulation rate for BATTERY_STORAGE tariff.

```
RegulationRate secondsRegulationRate = new RegulationRate().withResponse(ResponseTime.SECONDS)
    .withUpRegulationPayment(1000).withDownRegulationPayment(-1000);
Rate normalRate = new Rate().withFixed(true).withValue(-0.40);
TariffSpecification specification =
    new TariffSpecification(this.broker.getBroker(), PowerType.BATTERY_STORAGE)
        .withMinDuration(14).withEarlyWithdrawPayment(-20).withSignupPayment(10)
        .addRate(secondsRegulationRate).addRate(normalRate);
this.broker.sendMessage(specification);
```

The result of the above tariff is, almost all BATTERY_STORAGE customer sign up for this tariff. In addition, when down regulation happens, the customers pay the broker a very expensive prices. 

<img width="1109" alt="screen shot 2017-10-01 at 12 38 42 am" src="https://user-images.githubusercontent.com/5508096/31047647-f448a1a6-a640-11e7-8d9d-5feecd35aba4.png">

I wonder if the above scenario is related to this bug? Once I understand this scenario, a simple way to win the cash position, is by submitting the above tariff, earn the 3 million dollar, and revoke a tariffs and stop participating in all markets, and wait for the end of the game.

**Comment by Andyccs** [comment]
On another attempt, I was trying to use the above scenario, and send a unreasonable balancing order to balance market.

```
if (timeslot == 360) {
  RegulationRate secondsRegulationRate = new RegulationRate().withResponse(ResponseTime.SECONDS)
      .withUpRegulationPayment(1000).withDownRegulationPayment(-1000);
  Rate normalRate = new Rate().withFixed(true).withValue(-0.40);
  TariffSpecification specification =
      new TariffSpecification(this.broker.getBroker(), PowerType.BATTERY_STORAGE)
          .withMinDuration(14).withEarlyWithdrawPayment(-20).withSignupPayment(10)
          .addRate(secondsRegulationRate).addRate(normalRate);
  this.broker.sendMessage(specification);
}

if (timeslot == 362) {
  // Up-regulate, deficit in energy, discharge battery, most likely I will be paid to balance
  // market, but will pay the customer
  // Cash flow: Balance market -> broker -> customer
  BalancingOrder upRegulatedOrder = new BalancingOrder(this.broker.getBroker(),
      this.batteryStorageTariffSpecification, 1.4, 1000);
  // Down-regulate, surplus in energy, charge battery, most likely I will pay to balance market,
  // but get paid by the customer.
  // Cash flow: customer -> broker -> balance market
  BalancingOrder downRegulatedOrder = new BalancingOrder(this.broker.getBroker(),
      this.batteryStorageTariffSpecification, -0.4, -1000);
  this.broker.sendMessage(upRegulatedOrder);
  this.broker.sendMessage(downRegulatedOrder);
}
```

The result of the above codes still give me the same cash position graph.

**Comment by jecollins** [comment]
Hello, Andy. Thanks for the details. Was the balancing order in your first example the same as in the second example? It would help me work up a test case for this.

**Comment by Andyccs** [comment]
For the first comment, the balancing orders are on the range of -0.2 and 0.1. I have forgot the exact rates.

**Comment by jecollins** [comment]
In the current server, the balancing order for this tariff would be automatically constructed from the regulation rate (see #946, and Section 6 of the [2018 specification](https://ssrn.com/abstract=3087096)). With extreme prices such as your example, it's unlikely the up-regulation offers would ever clear the market. The down-regulation offers would clear every time the market was oversupplied, but you might not make any money on them when other brokers see what you are doing and run up their down-regulation prices.

From the standpoint of the battery, those prices are a wash, because the battery will expect equal quantities of up-regulation and down-regulation over time. When running this test with a single broker, you could be fooled if your broker is consistently unbalanced in one direction or the other. On the other hand, it seems silly for a customer to accept down-regulation prices higher than consumption prices. I'll look into that.

**Comment by jecollins** [comment]
BTW, your tariff example has a minDuration of 14 msec. If you want 14 days, multiply by TimeService.DAY.

**Comment by jecollins** [comment]
I'm not sure what version of the server you are using. The current 1.5.0-SNAPSHOT, being prepared for the 2018 competition, does not allow ResponseTime.SECONDS, only ResponseTime.MINUTES.

**Comment by jecollins** [comment]
A little more thought suggests that customers should not offer down-regulation if they would have to pay more than the consumption rate for it. The question is whether this decision should be made at tariff-evaluation time or per-timeslot. Doing it at eval time might reject otherwise attractive tariffs.

**Comment by jecollins** [comment]
evcustomer now initializes its tariff evaluator, and correctly subscribes to EV tariffs. Also, customers now disregard regulation when evaluating tariffs with extreme regulation rates, and don't post regulation capacities if subscribed to such a tariff.
