### ISSUE TITLE
Weather Server sends "id" which means "offset" but isn't globally precise?

### ISSUE THREAD

**Issue by pascalwhoop** [powertac/powertac-server#959]
Hi,
I was trying to wrap my head around the weather generation.

according to the [WeatherService](https://github.com/powertac/powertac-server/blob/c47de119a8e8665477d21256a73e6867b202cdd8/server-main/src/main/java/org/powertac/server/WeatherService.java#L503-L517), an `id` field is expected in the `weatherForecast` nodes. This is then passed into the [constructor](https://github.com/powertac/powertac-core/blob/f5b6cb423071d10aacdbd3365f95791cf896d47d/common/src/main/java/org/powertac/common/WeatherForecastPrediction.java#L58-L68) of the `WeatherForecastPrediction` where it is used as such

```
public WeatherForecastPrediction (int time, double temperature,
                                    double windSpeed, double windDirection,
                                    double cloudCover)
  {
    super();
    this.forecastTime = time;
    this.temperature = temperature;
    this.windSpeed = windSpeed;
    this.windDirection = windDirection;
    this.cloudCover = cloudCover;
  }
```

So it seems, the `id` value is used as the `forecastTime` value. Sounds a bit ugly but if it works OK, I won't judge code that has worked for years. 

But what makes me scratch my head is this:
```
/** the offset from the forecast timeslot for which the weather is predicted */
  @XStreamAsAttribute
private int forecastTime;
```
there is no date associated with the forecast object. I haven't written an agent yet, so I don't know the exact process but does this `forecastTime` basically mean "forecast for X days from now"? In this case, how does the server handle the situation in which the weather data is passed as a file as [these lines of code suggest is possible](https://github.com/powertac/powertac-server/blob/5eff83930bdfb1a60c1db9f7b7c59677c7ca3254/server-main/src/main/java/org/powertac/server/CompetitionSetupService.java#L174-L175)? If the file holds hundreds of thousands of forecasts and the actual weatherReports have no ID, how does the server pick "the right ones" out of the bunch for each day without any date data? In the "server request approach" (i.e. with a weather server answering queries), the date for the forecast is implicit through the query but not actually present in the underlying data transmitted. 

If I just didn't look in the right spots, let me know.
Cheers,
Pascal

**Comment by govertbuijs** [comment]
Hi Pascal,

Working from memory here, but IIRC the forecasts are for the next 24 hours per originating point in time.
So for each 'origin' hour you get 24 forecasts, ranging from 1 to 24 hours in the future.
Those are id-ed 1-24, but also contain the date for which the forecast is.

Does that make sense?

Cheers,

Govert

**Comment by jecollins** [comment]
The ID value for WeatherForecastPrediction and other domain types is automatically generated by calls to `IdGenerator.createId()`. This guarantees unique ID values in the simulation environment. But the Weather Server is outside the sim environment, so whatever it puts in this field is very likely overridden in the server anyway. I don't see that there's a bug here.
