### ISSUE TITLE
Visualizer replay should allow for rate control

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#964]
Currently, when we replay a game through the visualizer, it's not really possible to interact with the graphs while the data is being loaded. This is because the visualizer is typically compute-bound receiving messages and rendering plots. It would be helpful to allow for "pacing" such as a minimum time per timeslot. This time could be much less than the normal 5 seconds, but might be 1 or 2 seconds. This would make it much easier to use the visualizer as a demonstration tool.

**Comment by jecollins** [comment]
I fixed DomainObjectReader to optionally pause before processing TimeslotUpdate messages. This is a good approximation of how time passes in boot or sim sessions. Since the Viz interacts with LogtoolCore, I added a delegation interface to allow the viz to set the delay, and I hard-coded LogtoolExecutor to set the delay to 1000 msec before calling LogtoolCore.readStateLog(). It works well, probably could be less than 1 sec, but 1 sec is short enough to see a fair amount of variation in the time needed to display data from each new timeslot. But it works and you can interact with it while it's running.

So the question is whether the hard-coded approach is enough (it's a bit obscure), or whether there should be some way to set the delay without re-compiling powertac-server. The config does not get used for this case, so you cannot put the value in a @ConfigurableValue, and the Viz does not take command-line args AFAIK. That seems to leave us with a box to fill in on the UI, which seems like overkill. Other ideas?

**Comment by erikkemperman** [comment]
@jecollins  See https://github.com/powertac/powertac-server/pull/969

**Comment by jecollins** [comment]
OK, I see a PR for server-distribution, but I don't understand how to use this feature. We need to update the README.md to explain it.

**Comment by jecollins** [comment]
OK, I figured it out, and it works. I'll update the README.

**Comment by erikkemperman** [comment]
Thanks!
