### ISSUE TITLE
Temperature data is time-offset in some 2018 tournament games

### ISSUE THREAD

**Issue by jecollins** [powertac/powertac-server#975]
See [Easwar's report on Nabble](http://power-tac-developers.975333.n3.nabble.com/Issue-in-temperature-day-time-and-solar-production-td4026820.html#a4026823). It appears that the temperature data is about 6 hours off in this game.

**Comment by govertbuijs** [comment]
It's a mess. 
It seems the weather server produces the reports based on UTC, but the forecasts based on local time.
The sim requests appear to be for local time (see post Easwar). 

I'll convert the data for the weather server to match the requests from the sim.
I'm not sure how DST is handled, or if that's even relevant.

**Comment by govertbuijs** [comment]
This should be fixed now.
