### ISSUE TITLE
Build Error with gulp

### ISSUE THREAD

**Issue by StevenShi-23** [powertac/powertac-server#984]
Hi,

First of all, many thanks to @erikkemperman for your prompt response on the bower issue!

Unfortunately,  another issue occurs following bower's fix, and this one is related to `gulp`.

The error message is as the following:

```
[INFO] [15:48:51] Finished 'styles' after 15 ms
[INFO] [15:48:51] Finished 'images' after 70 ms
[INFO] [15:48:51] gulp-imagemin: Minified 0 images
[INFO] [15:48:51] Finished 'html' after 249 ms
[INFO] [15:48:51] Starting 'assets:prod'...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.514 s
[INFO] Finished at: 2018-10-24T15:48:59Z
[INFO] Final Memory: 23M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:gulp (gulp build) on project visualizer2: Failed to run task: 'gulp.js build --no-notification' failed. (error code 137) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

According to [another issue](https://github.com/eirslett/frontend-maven-plugin/issues/536), this should have been fixed. Indeed, gulp v3.9.1 worked on my Mac. My ubuntu container used the same version of gulp, so I tried `$ gulp build` under /visualizer2, but the following error occurs:

```
[15:58:11] Starting 'copy:images'...
[15:58:11] Finished 'copy:images' after 8.76 ms
[15:58:11] Finished 'styles' after 14 ms
[15:58:11] gulp-notify: [JHipster Gulp Build] Error: spawn /home/ubuntu/powertac/server/powertac-server-powertac-server-1.5.0/visualizer2/node_modules/optipng-bin/vendor/optipng ENOENT
[15:58:11] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
[15:58:11] Finished 'images' after 74 ms
[15:58:11] gulp-notify: [JHipster Gulp Build] Error: spawn /home/ubuntu/powertac/server/powertac-server-powertac-server-1.5.0/visualizer2/node_modules/optipng-bin/vendor/optipng ENOENT
[15:58:11] gulp-notify: [Error running notifier] Could not send message: notify-send must be installed on the system.
[15:58:11] gulp-imagemin: Minified 0 images
[15:58:12] Finished 'html' after 252 ms
[15:58:12] Starting 'assets:prod'...
[15:58:28] Finished 'assets:prod' after 17 s
[15:58:28] Finished 'build' after 17 s
```
There are two errors: could not send message, and cannot find optipng. I fixed the first error by following [this post](https://stackoverflow.com/questions/31431503/gulp-notify-error-in-notifier-error-in-plugin-gulp-notify-not-found-notify/38559846).  And I fixed second error by `npm install optipng-bin`. Now I can do `gulp build` visualizer2, but `$mvn clean build` under root directory still failed. It stopped at `Starting 'assets:prod'...`.

I wonder that is the legitimate way to do it, and I would appreciate the insights from you developers. 

Thanks!

**Comment by erikkemperman** [comment]
One of these days I should really upgrade the visualizer to the latest jhipster version. It will likely get rid of a lot of these rough edges -- but it's an awful lot of work... Glad you have a working build now, hopefully next time it will be a bit smoother!

**Comment by StevenShi-23** [comment]
😃 Sure. I can work with the build on my laptop anyway. Thanks for the communications!

**Comment by jecollins** [comment]
Is this still an issue? I've been building frequently over the past few weeks, and have not seen this.

**Comment by erikkemperman** [comment]
I am not sure what more we can do, havent been able to reproduce myself. But didn’t want to close an issue some one else opened. @StevenShi-23?

**Comment by StevenShi-23** [comment]
Sure, it should be fixable. Thank you @erikkemperman.
